theme: jekyll-theme-minimal
title: [Characterizing the growth of Tor network over time]
description: [Using Tor consensus data https://consensus-health.torproject.org. Also correlating with BGPStream data to identify possible cases of Tor relays having their IP addresses hijacked.]
